perf: controllers logic refactored, removing the nested conditions
ivnagst/API-CPF-Validator pull request #13
Opened 2022-12-20 02:58 UTC by ivnagst

solves #5

2022-12-20 09:28 UTC, Farenheith requested changes
Comentei em alguns pontos, mas outros estão com as mesmas questões apontadas, então pega o que foi comentado no código e revisa todos os lugares.

Fora isso, acho melhor testar melhor a solução.
Tenta bloquear um CPF inválido, depois vai no banco e olha se foi salvo

2022-12-20 09:28 UTC, Farenheith commented on tsconfig.json
> -		"experimentalDecorators": true,
As mudanças neste arquivo foram necessárias?

2022-12-20 09:28 UTC, Farenheith commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
A criação desse arquivo é necessária neste pr ou no próximo?

2022-12-20 09:28 UTC, Farenheith commented on src/controllers/cpfsController.ts
>  			res.send({ message: 'O CPF informado não é valido.' });
Independente de ter caído nesse If, ele vai fazer find no banco logo em seguida. Isso é intencional?

2022-12-20 09:28 UTC, Farenheith commented on src/controllers/cpfsController.ts
> +			res.send({ message: 'O CPF já encontra-se bloquado.' });
Independente de cair nesse If. Ele vai salvar no banco

2022-12-20 09:28 UTC, Farenheith commented on src/controllers/cpfsController.ts
> +			res.status(200).send({ message: 'O CPF informado não é valido!' });
Independente de cair nesse If, ele vai pesquisar no banco

2022-12-20 09:28 UTC, Farenheith commented on src/controllers/cpfsController.ts
>  				message: 'O CPF informado não encontra-se bloqueado!',
Independente de cair nesse If, ele vai salvar no banco

2022-12-23 01:46 UTC, ivnagst commented on tsconfig.json
> -		"experimentalDecorators": true,
Não.

2022-12-23 01:47 UTC, ivnagst commented on src/controllers/cpfsController.ts
>  			res.send({ message: 'O CPF informado não é valido.' });
Não. Isto foi errado d+

2022-12-23 01:47 UTC, ivnagst commented on src/controllers/cpfsController.ts
> +			res.send({ message: 'O CPF já encontra-se bloquado.' });
Sim, ja corrigi.

2022-12-23 01:48 UTC, ivnagst commented on src/controllers/cpfsController.ts
> +			res.status(200).send({ message: 'O CPF informado não é valido!' });
Sim. Ja corrigi.

2022-12-23 01:48 UTC, ivnagst commented on src/controllers/cpfsController.ts
>  				message: 'O CPF informado não encontra-se bloqueado!',
Sim. Ja corrigi.

2022-12-23 01:51 UTC, closed without merging