refactor: refactoring of the logic of the controllers, performed the removal of nested conditions, routes and data persistence in Mongo verified
ivnagst/API-CPF-Validator pull request #14
Opened 2022-12-23 12:00 UTC by ivnagst

solves #5

2022-12-26 11:30 UTC, Farenheith requested changes

2022-12-26 11:30 UTC, Farenheith commented on src/controllers/cpfValidator.ts
> +  let strCPF: string = String(cpf).replace(/[^0-9]/g,'').slice(0,11); // Pqp, fiquei um tempo ate conseguir resolver isto!
Remover comentários com palavrões do código

2022-12-26 11:30 UTC, Farenheith commented on src/app.ts
> +db.on("error", console.log.bind(console, 'Erro de conexão'));
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:30 UTC, Farenheith commented on src/app.ts
> +    console.log("Conexão com o banco de dados realizada com sucesso :D");
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:30 UTC, Farenheith commented on src/config/dbConnect.ts
> +mongoose.connect("mongodb+srv://root:123123123@cluster0.kssgfqn.mongodb.net/cpfValidator")
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:30 UTC, Farenheith commented on tsconfig.json
>  	"compilerOptions": {
Há mudanças desnecessárias aqui. a do target para ES2022, tudo bem. As outras, são realmente necessárias pra esse PR?

2022-12-26 11:30 UTC, Farenheith commented on src/server.ts
> +import app from "./app"
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:30 UTC, Farenheith commented on src/config/dbConnect.ts
> +import mongoose from "mongoose";
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:30 UTC, Farenheith commented on src/app.ts
> +import routes from "./routes/index";
Padronizar estilo de aspas. Usa tudo como simples, que é o que está especificado no eslintrc.json

2022-12-26 11:35 UTC, ivnagst commented on src/controllers/cpfValidator.ts
> +  let strCPF: string = String(cpf).replace(/[^0-9]/g,'').slice(0,11); // Pqp, fiquei um tempo ate conseguir resolver isto!
Perdão, não foi por mal.

2022-12-26 11:36 UTC, ivnagst commented on src/app.ts
> +db.on("error", console.log.bind(console, 'Erro de conexão'));
ok

2022-12-26 11:36 UTC, ivnagst commented on src/app.ts
> +    console.log("Conexão com o banco de dados realizada com sucesso :D");
ok

2022-12-26 11:36 UTC, ivnagst commented on src/config/dbConnect.ts
> +mongoose.connect("mongodb+srv://root:123123123@cluster0.kssgfqn.mongodb.net/cpfValidator")
ok

2022-12-26 11:36 UTC, ivnagst commented on tsconfig.json
>  	"compilerOptions": {
Irei revisar.

2022-12-26 11:37 UTC, ivnagst commented on src/server.ts
> +import app from "./app"
ok

2022-12-26 11:37 UTC, ivnagst commented on src/config/dbConnect.ts
> +import mongoose from "mongoose";
ok

2022-12-26 11:37 UTC, ivnagst commented on src/app.ts
> +import routes from "./routes/index";
ok

2022-12-27 01:25 UTC, Farenheith approved these changes

2022-12-27 01:35 UTC, merged