feat: using inversify and dependency injection to a better http structure
ivnagst/API-CPF-Validator pull request #17
Opened 2023-01-09 20:01 UTC by ivnagst

solves #11

2023-01-09 22:25 UTC, Farenheith requested changes

2023-01-09 22:25 UTC, Farenheith commented on package.json
>  		"start:dev": "ts-node-dev './src/index.ts'",
acho que precisa atualizar pra src/ap.ts tb o start:dev

2023-01-10 02:16 UTC, ivnagst commented on package.json
>  		"start:dev": "ts-node-dev './src/index.ts'",
Ok.

2023-01-12 16:17 UTC, ivnagst commented
A última branch, não inclui as alterações que conversamos no fim da segunda feira. pois não estão no escopo do card.

2023-01-12 16:52 UTC, Farenheith approved these changes

2023-01-12 20:38 UTC, merged