refactor: improved database connection algorithm
ivnagst/API-CPF-Validator pull request #20
Opened 2023-01-13 03:01 UTC by ivnagst

solves #19

2023-01-13 10:48 UTC, Farenheith commented
Isso não resolveu o problema que conversamos, Ivan. Ter criado a classe DBConnection apenas transferiu o problema do mongoose para ela. O problema que tinhamos falado é: a aplicação pode começar a escutar a porta http ANTES de conectar no banco?
Com o seu código, isso ainda pode acontecer? Neste caso a resposta é sim, então ainda não está correto.

Avalia melhor o que precisa ser feito aí para garantir que vc começará a escutar a porta só depois que a conexão estiver estabelecida.

2023-01-13 10:49 UTC, Farenheith requested changes

2023-01-13 10:49 UTC, Farenheith commented on src/config/dbConnect.ts
> +	public async connect(): Promise<mongoose.Connection> {
Esse connnect não impede que a posta http da aplicação comece a ser escutada antes da conexão com o banco estar estabelecida.

2023-01-14 21:11 UTC, ivnagst commented on src/config/dbConnect.ts
> +	public async connect(): Promise<mongoose.Connection> {
Em algum momento do restante da minha vida neste mundo, a minha dislexia vai acabar me matando.

2023-01-15 11:58 UTC, Farenheith approved these changes

2023-01-16 11:58 UTC, merged