performed the correct use of dependency injection, implementation of process.env and project startup setup adjustment
ivnagst/API-CPF-Validator pull request #23
Opened 2023-01-30 16:11 UTC by ivnagst

solves #22

2023-01-31 11:37 UTC, Farenheith requested changes

2023-01-31 11:37 UTC, Farenheith commented on package.json
>  	"main": "src/app.ts",
O main precis ser alterado tb. Veja que o main n deve ser o src/index.ts, as sim o index.js que é gerado no build do projeto

2023-01-31 11:37 UTC, Farenheith commented on src/services/cpfServices.ts
> +const requestCounter = new RequestCounter();
É legal a ideia de crir essa classe, mas se vc tá trabalhando com injeção de dependencia, prefira injetá-la, ao invés de instanciar na mão.
Então, joga a classe para um arquivo separado, faz o bind no myContainer, e aí injeta ela no CpfServices ou onde quiser injetar.
Não esquece do injectable pra ela poder ser injetatável

2023-01-31 11:49 UTC, ivnagst commented on package.json
>  	"main": "src/app.ts",
Falta de atenção.

2023-02-01 01:06 UTC, ivnagst commented on src/services/cpfServices.ts
> +const requestCounter = new RequestCounter();
Justo!

2023-02-01 13:08 UTC, Farenheith requested changes

2023-02-01 13:08 UTC, Farenheith commented on package.json
> +	"main": "src/index.ts",
Ivan, o que eu tinha falado é que o main tem que ser o index gerado pela compilação, e não o ts.
Dá uma olhada no path do index.js que é gerado a partir do src/index.ts, esse tem que ser o main

2023-02-02 00:51 UTC, Farenheith approved these changes

2023-02-02 01:20 UTC, merged