Correções realizadas, que alegria!
ivnagst/API-CPF-Validator pull request #4
Opened 2022-11-29 00:31 UTC by ivnagst

Consegui implementar a verificação para quando o CPF ja existe no model e também a contagem de dos docs logo na primeira requisição. 

Paga um dogão daquele lá pra gente!

2022-11-29 00:46 UTC, Farenheith requested changes
O código parece funcionar mas as condições não estão em uma ordem favorável. Se você reorganizar os seus ifs, consegue deixar eles mais simples e o código mais limpo.
A primeira coisa que deveria fazer é validar se o CPF é válido, porque se não for, nem é é necessário checar se está na base.
Se for, aí cheque se está na base. Se estiver, da erro
Finalmente, se nada do que foi dito acima acontecer, você pode salvar no banco

2022-11-30 01:31 UTC, Farenheith requested changes
A organização ficou melhor, mas vejo vários ifs redundantes. Se você já fez uma validação que uma condição é true, há necessidade de outra validação pra checar se ela é false?
Vi isso se repetindo ao longo do código. Reavalia o fluxo de código que você tá fazendo para não colocar condições desnecessárias

2022-11-30 01:31 UTC, Farenheith commented on src/controllers/cpfsController.js
> +                    if (err) {
Este If é realmente necessário?

2022-11-30 01:31 UTC, Farenheith commented on src/controllers/cpfsController.js
> +            if (verifier > 0) {
Esse If é realmente necessário?

2022-11-30 01:31 UTC, Farenheith commented on src/controllers/cpfsController.js
> +        if (isValid(cpfToLock.cpf) === false) {
Esse If é realmente necessário?

2022-11-30 01:39 UTC, ivnagst commented on src/controllers/cpfsController.js
> +                    if (err) {
Testei e não faz sentido mante-lo.

2022-11-30 01:47 UTC, ivnagst commented on src/controllers/cpfsController.js
> +            if (verifier > 0) {
Eu poderia utilizar um else no local desta verificação, inclusive, já havia utilizado desta forma em outro momento do código. 

Ambos funcionam neste algoritimo, embora o if não seja necessário, de fato.

2022-11-30 01:49 UTC, ivnagst commented on src/controllers/cpfsController.js
> +        if (isValid(cpfToLock.cpf) === false) {
A mesma ideia do comentário anterior. Em outro momento, utilizei um else aqui. Ambos funcionam e o if **não** é necessário.

2022-11-30 10:27 UTC, Farenheith approved these changes

2022-11-30 10:30 UTC, merged